### ISSUE TITLE
Changing Sample rate

### ISSUE THREAD

**Issue by Tom-AW** [Protocentral/protocentral-ads1292r-arduino#3]
In ecgRespirationAlgo.h the sample rate is set as 125 Hz
![image](https://user-images.githubusercontent.com/45534386/116879200-444cab80-ac18-11eb-8ce6-2fd7e5ce7276.png)
and the drdy pin pulses on my oscilloscope every 8mS as would be expected, however if I change this value to 2000 making it 2kHz which the AD1292R is capable of doing, the pulses are still 8 mS apart, is there another variable I need to change in order to change the sample rate of the device?

I've had a look through the files and can't see something that stands out as needing to be modified other than that value mentioned before, any help would be appreciated.

I'm using the breakout board not the shield.

**Comment by joicetm** [comment]
Hi,

You will have to configure the CONFIG1 register with appropriate value for that.
That macro is not used for ads1292r initialization. 
Please have a look at the datasheet for more information.

![config1_Reg](https://user-images.githubusercontent.com/27211252/117598773-127e9c00-b166-11eb-8ecb-625814e71da4.png)
